import type Database from "@tauri-apps/plugin-sql";

type SeedBiomarker = {
  code?: string;
  name: string;
  category: string;
  aliases: string[];
  unit: string;
  ref?: [number | null, number | null];
  optimal?: [number | null, number | null];
  direction?: "higher_better" | "lower_better" | "range";
};

/**
 * Seed reference dictionary (general adult ranges; labs and individual context
 * always take precedence). Aliases cover common synonyms, abbreviations and
 * Russian translations — they feed the deterministic import mapper, so the
 * richer this list, the fewer AI fallback calls the pipeline needs.
 */
const SEED: SeedBiomarker[] = [
  // ── Complete blood count ──
  {
    code: "718-7",
    name: "Hemoglobin",
    category: "Complete Blood Count",
    unit: "g/L",
    ref: [130, 170],
    aliases: ["hgb", "hb", "haemoglobin", "гемоглобин"],
  },
  {
    code: "4544-3",
    name: "Hematocrit",
    category: "Complete Blood Count",
    unit: "%",
    ref: [40, 50],
    aliases: ["hct", "haematocrit", "гематокрит"],
  },
  {
    code: "789-8",
    name: "Red Blood Cells",
    category: "Complete Blood Count",
    unit: "10^12/L",
    ref: [4.3, 5.7],
    aliases: ["rbc", "erythrocytes", "эритроциты", "red blood cell count"],
  },
  {
    code: "6690-2",
    name: "White Blood Cells",
    category: "Complete Blood Count",
    unit: "10^9/L",
    ref: [4, 9],
    aliases: ["wbc", "leukocytes", "лейкоциты", "white blood cell count"],
  },
  {
    code: "777-3",
    name: "Platelets",
    category: "Complete Blood Count",
    unit: "10^9/L",
    ref: [150, 400],
    aliases: ["plt", "thrombocytes", "тромбоциты", "platelet count"],
  },
  {
    code: "787-2",
    name: "MCV",
    category: "Complete Blood Count",
    unit: "fL",
    ref: [80, 100],
    aliases: ["mean corpuscular volume", "средний объем эритроцита"],
  },
  {
    code: "785-6",
    name: "MCH",
    category: "Complete Blood Count",
    unit: "pg",
    ref: [27, 34],
    aliases: ["mean corpuscular hemoglobin", "среднее содержание гемоглобина в эритроците"],
  },
  {
    code: "786-4",
    name: "MCHC",
    category: "Complete Blood Count",
    unit: "g/L",
    ref: [320, 360],
    aliases: [
      "mean corpuscular hemoglobin concentration",
      "средняя концентрация гемоглобина в эритроците",
    ],
  },
  {
    code: "788-0",
    name: "RDW",
    category: "Complete Blood Count",
    unit: "%",
    ref: [11.5, 14.5],
    aliases: ["red cell distribution width", "rdw-cv", "ширина распределения эритроцитов"],
  },
  {
    code: "770-8",
    name: "Neutrophils",
    category: "Complete Blood Count",
    unit: "%",
    ref: [40, 70],
    aliases: ["neut", "neutrophils %", "нейтрофилы", "сегментоядерные нейтрофилы"],
  },
  {
    code: "736-9",
    name: "Lymphocytes",
    category: "Complete Blood Count",
    unit: "%",
    ref: [20, 40],
    aliases: ["lymph", "lymphocytes %", "лимфоциты"],
  },
  {
    code: "5905-5",
    name: "Monocytes",
    category: "Complete Blood Count",
    unit: "%",
    ref: [2, 10],
    aliases: ["mono", "monocytes %", "моноциты"],
  },
  {
    code: "713-8",
    name: "Eosinophils",
    category: "Complete Blood Count",
    unit: "%",
    ref: [1, 5],
    aliases: ["eos", "eosinophils %", "эозинофилы"],
  },
  {
    code: "706-2",
    name: "Basophils",
    category: "Complete Blood Count",
    unit: "%",
    ref: [0, 1.5],
    aliases: ["baso", "basophils %", "базофилы"],
  },
  {
    code: "30341-2",
    name: "ESR",
    category: "Complete Blood Count",
    unit: "mm/h",
    ref: [0, 15],
    direction: "lower_better",
    aliases: ["erythrocyte sedimentation rate", "соэ", "скорость оседания эритроцитов", "sed rate"],
  },

  // ── Glucose metabolism ──
  {
    code: "1558-6",
    name: "Glucose (fasting)",
    category: "Glucose Metabolism",
    unit: "mmol/L",
    ref: [3.9, 5.6],
    optimal: [4.2, 5.0],
    aliases: [
      "glucose",
      "fasting glucose",
      "blood sugar",
      "глюкоза",
      "глюкоза натощак",
      "сахар крови",
    ],
  },
  {
    code: "4548-4",
    name: "HbA1c",
    category: "Glucose Metabolism",
    unit: "%",
    ref: [4, 5.7],
    optimal: [4.5, 5.3],
    direction: "lower_better",
    aliases: [
      "glycated hemoglobin",
      "hemoglobin a1c",
      "a1c",
      "гликированный гемоглобин",
      "гликогемоглобин",
    ],
  },
  {
    code: "20448-7",
    name: "Insulin (fasting)",
    category: "Glucose Metabolism",
    unit: "µIU/mL",
    ref: [2.6, 24.9],
    optimal: [2, 8],
    direction: "lower_better",
    aliases: ["insulin", "инсулин", "инсулин натощак"],
  },
  {
    code: "14933-6",
    name: "Uric Acid",
    category: "Glucose Metabolism",
    unit: "µmol/L",
    ref: [200, 420],
    optimal: [200, 360],
    aliases: ["urate", "мочевая кислота"],
  },

  // ── Lipid panel ──
  {
    code: "2093-3",
    name: "Total Cholesterol",
    category: "Lipid Panel",
    unit: "mmol/L",
    ref: [2.9, 5.2],
    aliases: [
      "cholesterol",
      "cholesterol total",
      "холестерин",
      "холестерин общий",
      "общий холестерин",
    ],
  },
  {
    code: "13457-7",
    name: "LDL Cholesterol",
    category: "Lipid Panel",
    unit: "mmol/L",
    ref: [1.4, 3.0],
    direction: "lower_better",
    aliases: ["ldl", "ldl-c", "лпнп", "холестерин лпнп", "low density lipoprotein"],
  },
  {
    code: "2085-9",
    name: "HDL Cholesterol",
    category: "Lipid Panel",
    unit: "mmol/L",
    ref: [1.0, 2.2],
    direction: "higher_better",
    aliases: ["hdl", "hdl-c", "лпвп", "холестерин лпвп", "high density lipoprotein"],
  },
  {
    code: "2571-8",
    name: "Triglycerides",
    category: "Lipid Panel",
    unit: "mmol/L",
    ref: [0.4, 1.7],
    optimal: [0.4, 1.0],
    direction: "lower_better",
    aliases: ["tg", "trig", "триглицериды"],
  },
  {
    code: "1884-6",
    name: "Apolipoprotein B",
    category: "Lipid Panel",
    unit: "g/L",
    ref: [0.6, 1.2],
    optimal: [0.4, 0.8],
    direction: "lower_better",
    aliases: ["apob", "apo b", "аполипопротеин b", "аполипопротеин в"],
  },
  {
    code: "10835-7",
    name: "Lipoprotein(a)",
    category: "Lipid Panel",
    unit: "nmol/L",
    ref: [0, 75],
    direction: "lower_better",
    aliases: ["lp(a)", "lpa", "липопротеин (а)", "липопротеин а"],
  },

  // ── Liver ──
  {
    code: "1742-6",
    name: "ALT",
    category: "Liver",
    unit: "U/L",
    ref: [7, 41],
    optimal: [10, 26],
    direction: "lower_better",
    aliases: ["alanine aminotransferase", "sgpt", "алт", "аланинаминотрансфераза"],
  },
  {
    code: "1920-8",
    name: "AST",
    category: "Liver",
    unit: "U/L",
    ref: [10, 40],
    optimal: [12, 26],
    direction: "lower_better",
    aliases: ["aspartate aminotransferase", "sgot", "аст", "аспартатаминотрансфераза"],
  },
  {
    code: "2324-2",
    name: "GGT",
    category: "Liver",
    unit: "U/L",
    ref: [8, 61],
    optimal: [8, 25],
    direction: "lower_better",
    aliases: ["gamma-glutamyl transferase", "ggtp", "ггт", "гамма-глутамилтрансфераза", "ггтп"],
  },
  {
    code: "6768-6",
    name: "Alkaline Phosphatase",
    category: "Liver",
    unit: "U/L",
    ref: [40, 130],
    aliases: ["alp", "alk phos", "щф", "щелочная фосфатаза"],
  },
  {
    code: "1975-2",
    name: "Bilirubin Total",
    category: "Liver",
    unit: "µmol/L",
    ref: [5, 21],
    aliases: ["total bilirubin", "билирубин общий", "общий билирубин"],
  },
  {
    code: "1968-7",
    name: "Bilirubin Direct",
    category: "Liver",
    unit: "µmol/L",
    ref: [0, 5],
    aliases: ["direct bilirubin", "conjugated bilirubin", "билирубин прямой", "прямой билирубин"],
  },
  {
    code: "1751-7",
    name: "Albumin",
    category: "Liver",
    unit: "g/L",
    ref: [35, 52],
    optimal: [42, 50],
    aliases: ["альбумин"],
  },
  {
    code: "2885-2",
    name: "Total Protein",
    category: "Liver",
    unit: "g/L",
    ref: [64, 83],
    aliases: ["protein total", "белок общий", "общий белок"],
  },

  // ── Kidney ──
  {
    code: "2160-0",
    name: "Creatinine",
    category: "Kidney",
    unit: "µmol/L",
    ref: [62, 106],
    aliases: ["креатинин"],
  },
  {
    code: "3091-6",
    name: "Urea",
    category: "Kidney",
    unit: "mmol/L",
    ref: [2.8, 7.2],
    aliases: ["bun", "blood urea nitrogen", "мочевина"],
  },
  {
    code: "62238-1",
    name: "eGFR",
    category: "Kidney",
    unit: "mL/min/1.73m²",
    ref: [90, null],
    direction: "higher_better",
    aliases: ["gfr", "estimated gfr", "скф", "скорость клубочковой фильтрации", "расчетная скф"],
  },
  {
    code: "33863-2",
    name: "Cystatin C",
    category: "Kidney",
    unit: "mg/L",
    ref: [0.6, 1.1],
    direction: "lower_better",
    aliases: ["цистатин c", "цистатин с"],
  },

  // ── Electrolytes & minerals ──
  {
    code: "2951-2",
    name: "Sodium",
    category: "Electrolytes & Minerals",
    unit: "mmol/L",
    ref: [136, 145],
    aliases: ["na", "натрий"],
  },
  {
    code: "2823-3",
    name: "Potassium",
    category: "Electrolytes & Minerals",
    unit: "mmol/L",
    ref: [3.5, 5.1],
    aliases: ["k", "калий"],
  },
  {
    code: "17861-6",
    name: "Calcium",
    category: "Electrolytes & Minerals",
    unit: "mmol/L",
    ref: [2.15, 2.55],
    aliases: ["ca", "кальций", "кальций общий"],
  },
  {
    code: "19123-9",
    name: "Magnesium",
    category: "Electrolytes & Minerals",
    unit: "mmol/L",
    ref: [0.66, 1.07],
    optimal: [0.85, 1.05],
    aliases: ["mg", "магний"],
  },
  {
    code: "2777-1",
    name: "Phosphorus",
    category: "Electrolytes & Minerals",
    unit: "mmol/L",
    ref: [0.81, 1.45],
    aliases: ["phosphate", "фосфор", "фосфор неорганический"],
  },
  {
    code: "5763-8",
    name: "Zinc",
    category: "Electrolytes & Minerals",
    unit: "µmol/L",
    ref: [11, 18],
    aliases: ["zn", "цинк"],
  },

  // ── Iron status ──
  {
    code: "2276-4",
    name: "Ferritin",
    category: "Iron Status",
    unit: "µg/L",
    ref: [30, 400],
    optimal: [50, 150],
    aliases: ["ферритин"],
  },
  {
    code: "2498-4",
    name: "Iron",
    category: "Iron Status",
    unit: "µmol/L",
    ref: [11, 31],
    aliases: ["serum iron", "fe", "железо", "железо сывороточное", "сывороточное железо"],
  },
  {
    code: "3034-6",
    name: "Transferrin",
    category: "Iron Status",
    unit: "g/L",
    ref: [2, 3.6],
    aliases: ["трансферрин"],
  },
  {
    code: "2502-3",
    name: "Transferrin Saturation",
    category: "Iron Status",
    unit: "%",
    ref: [20, 45],
    aliases: [
      "tsat",
      "iron saturation",
      "насыщение трансферрина",
      "коэффициент насыщения трансферрина железом",
    ],
  },

  // ── Inflammation ──
  {
    code: "30522-7",
    name: "hs-CRP",
    category: "Inflammation",
    unit: "mg/L",
    ref: [0, 5],
    optimal: [0, 1],
    direction: "lower_better",
    aliases: [
      "crp",
      "c-reactive protein",
      "срб",
      "с-реактивный белок",
      "c-реактивный белок",
      "срб ультрачувствительный",
    ],
  },
  {
    code: "13965-9",
    name: "Homocysteine",
    category: "Inflammation",
    unit: "µmol/L",
    ref: [5, 15],
    optimal: [5, 8],
    direction: "lower_better",
    aliases: ["hcy", "гомоцистеин"],
  },
  {
    code: "3255-7",
    name: "Fibrinogen",
    category: "Inflammation",
    unit: "g/L",
    ref: [2, 4],
    aliases: ["фибриноген"],
  },

  // ── Thyroid ──
  {
    code: "3016-3",
    name: "TSH",
    category: "Thyroid",
    unit: "mIU/L",
    ref: [0.4, 4.0],
    optimal: [0.8, 2.5],
    aliases: ["thyroid stimulating hormone", "thyrotropin", "ттг", "тиреотропный гормон"],
  },
  {
    code: "3024-7",
    name: "Free T4",
    category: "Thyroid",
    unit: "pmol/L",
    ref: [12, 22],
    aliases: ["ft4", "free thyroxine", "т4 свободный", "свободный т4", "тироксин свободный"],
  },
  {
    code: "3051-0",
    name: "Free T3",
    category: "Thyroid",
    unit: "pmol/L",
    ref: [3.1, 6.8],
    aliases: [
      "ft3",
      "free triiodothyronine",
      "т3 свободный",
      "свободный т3",
      "трийодтиронин свободный",
    ],
  },
  {
    code: "8099-4",
    name: "Anti-TPO",
    category: "Thyroid",
    unit: "IU/mL",
    ref: [0, 34],
    direction: "lower_better",
    aliases: [
      "tpo antibodies",
      "thyroid peroxidase antibodies",
      "ат-тпо",
      "антитела к тиреопероксидазе",
    ],
  },
  {
    code: "8098-6",
    name: "Anti-TG",
    category: "Thyroid",
    unit: "IU/mL",
    ref: [0, 115],
    direction: "lower_better",
    aliases: ["tg antibodies", "thyroglobulin antibodies", "ат-тг", "антитела к тиреоглобулину"],
  },

  // ── Hormones ──
  {
    code: "2986-8",
    name: "Testosterone Total",
    category: "Hormones",
    unit: "nmol/L",
    ref: [8.6, 29],
    optimal: [18, 29],
    aliases: [
      "testosterone",
      "total testosterone",
      "тестостерон",
      "тестостерон общий",
      "общий тестостерон",
    ],
  },
  {
    code: "2991-8",
    name: "Testosterone Free",
    category: "Hormones",
    unit: "pmol/L",
    ref: [170, 600],
    aliases: ["free testosterone", "тестостерон свободный", "свободный тестостерон"],
  },
  {
    code: "13967-5",
    name: "SHBG",
    category: "Hormones",
    unit: "nmol/L",
    ref: [17, 66],
    aliases: ["sex hormone binding globulin", "гспг", "глобулин связывающий половые гормоны"],
  },
  {
    code: "14715-7",
    name: "Estradiol",
    category: "Hormones",
    unit: "pmol/L",
    ref: [40, 160],
    aliases: ["e2", "эстрадиол"],
  },
  {
    code: "2143-6",
    name: "Cortisol (morning)",
    category: "Hormones",
    unit: "nmol/L",
    ref: [170, 540],
    aliases: ["cortisol", "кортизол", "кортизол утренний"],
  },
  {
    code: "2191-5",
    name: "DHEA-S",
    category: "Hormones",
    unit: "µmol/L",
    ref: [2.4, 11.6],
    aliases: [
      "dhea sulfate",
      "dhea-so4",
      "дгэа-с",
      "дгэа сульфат",
      "дегидроэпиандростерон-сульфат",
    ],
  },
  {
    code: "2842-3",
    name: "Prolactin",
    category: "Hormones",
    unit: "mIU/L",
    ref: [86, 324],
    aliases: ["пролактин"],
  },
  {
    code: "10501-5",
    name: "LH",
    category: "Hormones",
    unit: "IU/L",
    ref: [1.7, 8.6],
    aliases: ["luteinizing hormone", "лг", "лютеинизирующий гормон"],
  },
  {
    code: "15067-2",
    name: "FSH",
    category: "Hormones",
    unit: "IU/L",
    ref: [1.5, 12.4],
    aliases: ["follicle stimulating hormone", "фсг", "фолликулостимулирующий гормон"],
  },
  {
    code: "2484-4",
    name: "IGF-1",
    category: "Hormones",
    unit: "ng/mL",
    ref: [88, 246],
    aliases: [
      "insulin-like growth factor 1",
      "somatomedin c",
      "игф-1",
      "ифр-1",
      "инсулиноподобный фактор роста",
    ],
  },
  {
    code: "2857-1",
    name: "PSA Total",
    category: "Hormones",
    unit: "ng/mL",
    ref: [0, 4],
    direction: "lower_better",
    aliases: [
      "psa",
      "prostate specific antigen",
      "пса",
      "пса общий",
      "простатспецифический антиген",
    ],
  },

  // ── Vitamins ──
  {
    code: "1989-3",
    name: "Vitamin D (25-OH)",
    category: "Vitamins",
    unit: "ng/mL",
    ref: [30, 100],
    optimal: [40, 60],
    aliases: [
      "vitamin d",
      "25-oh vitamin d",
      "25(oh)d",
      "calcidiol",
      "витамин d",
      "витамин д",
      "25-он витамин d",
      "витамин d (25-oh)",
    ],
  },
  {
    code: "2132-9",
    name: "Vitamin B12",
    category: "Vitamins",
    unit: "pg/mL",
    ref: [197, 771],
    optimal: [500, 900],
    aliases: ["b12", "cobalamin", "витамин b12", "витамин в12", "цианокобаламин", "кобаламин"],
  },
  {
    code: "2284-8",
    name: "Folate",
    category: "Vitamins",
    unit: "ng/mL",
    ref: [3.9, 26.8],
    optimal: [10, 25],
    aliases: ["folic acid", "vitamin b9", "фолиевая кислота", "фолаты", "витамин b9", "витамин в9"],
  },
];

export async function seedBiomarkersIfEmpty(conn: Database): Promise<void> {
  const [{ n }] = await conn.select<{ n: number }[]>("SELECT COUNT(*) AS n FROM biomarker");
  if (n > 0) return;

  await conn.execute("BEGIN");
  try {
    for (const b of SEED) {
      await conn.execute(
        `INSERT INTO biomarker
           (code, canonical_name, category, aliases, default_unit,
            ref_low, ref_high, optimal_low, optimal_high, direction, is_custom)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 0)`,
        [
          b.code ?? null,
          b.name,
          b.category,
          JSON.stringify(b.aliases),
          b.unit,
          b.ref?.[0] ?? null,
          b.ref?.[1] ?? null,
          b.optimal?.[0] ?? null,
          b.optimal?.[1] ?? null,
          b.direction ?? "range",
        ],
      );
    }
    await conn.execute("COMMIT");
  } catch (e) {
    await conn.execute("ROLLBACK");
    throw e;
  }
}
